### ISSUE TITLE
_read_row_from_packet decode non-utf-8 string will report error

### ISSUE THREAD

**Issue by ZhouJiaZhi** [PyMySQL/PyMySQL#1001]
when i execute 'show processlist', and the result contains non-utf-8 string, decode will report error 
```py
    def _read_row_from_packet(self, packet):
        row = []
        for encoding, converter in self.converters:
            try:
                data = packet.read_length_coded_string()
            except IndexError:
                # No more columns in this row
                # See https://github.com/PyMySQL/PyMySQL/pull/434
                break
            if data is not None:
                if encoding is not None:
>                   data = data.decode(encoding)
E                   UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 28: invalid start byte
```
converter  = None
data       = (b"update `some_table` set `some_field`='\x83\xa8a\x10\xabb\\\xcea(\\"
 b"\xe7\\\xec\xafc\\\xce\\0\x01k\x95'")
encoding   = 'utf8'
packet     = <pymysql.protocol.MysqlPacket object at 0x1098f1940>
row        = [2795, 'kkk', 'localhost:64188', 'kkk', 'Execute', 0, 'query end']
self       = <pymysql.connections.MySQLResult object at 0x1098ce668>

**Comment by methane** [comment]
It is defined behavior. If you want to use non UTF-8 string, you should use `use_unicode=False` option.

**Comment by est** [comment]
The problem is MySQLd will sometimes return packets with bytes not decodable in UTF-8, which makes them un-printable.

But instead of making the whole connection fail, I suggest we make utf-8 decoding optional.

https://github.com/PyMySQL/PyMySQL/blob/f24cb9aa7295921bcd8f34f752c8a05b981d3125/pymysql/connections.py#L1286

Change `data = data.decode(encoding)` to `data = data.decode(encoding, 'ignore')` will solve most of our problems, while maintaining compatibility.

**Comment by est** [comment]
For a temporary solution, I changed "INSERT INTO IGNORE..." to "INSERT INTO ... ON DUPLICATE KEYS UPDATE id=id"

Which is ugly, but it wont generate a `1062` warning, thus makes PyMySQL happy.

**Comment by methane** [comment]
> Change `data = data.decode(encoding)` to `data = data.decode(encoding, 'ignore')` will solve most of our problems, while maintaining 100% compatibility, avoid complete failures.

Silently ignore the data breakage is huge backward incompatibility.
Use `use_unicode=False` option.

**Comment by est** [comment]
> Silently ignore the data breakage is huge backward incompatibility.

How about this:

- without `"ignore"`, the PyMySQL connection certainly breaks, it's an unrecoverable and un-catchable error.
- with `"ignore"`, the program had a good good chance to go on

I skimmed through all issues with `_read_row_from_packet` on this github repo,  in most cases it's either error messages or warnings that's causing the decode error, when we writing programs we often catch error codes rather than string or regex match the message. So I assume `"ignore"` will **not** cause major problems, as the character decoding process is a purely character display problem, not a transactional data corruption problem. It's a good tradeoff to keep the MySQL connection up rather than totally give up.

> Use use_unicode=False option.

Oh boy I wish I could, PyMySQL is an upstream for many libraries or tools, for example ,the popular MyCLI, a MySQL client in python

https://github.com/dbcli/mycli/blob/832086bea3488b41118aa6e391f0d779b55be001/mycli/sqlexecute.py#L177

It explicitely set `use_unicode=True`, and it forbids a configuration or hackable way to change it. It would be a hard campaign to persuade everyone to change it.

**Comment by est** [comment]
> you should use binary, not string. Use CAST() or CONVERT().

Hi @methane  That's the crucial detail I am taking about. I did **NOT** give any bad encoding character to MySQLd, the 
MySQLd purposely returns an implicit warning message, which contains some invalid UTF8 bytes to the client during a **valid** `INSERT INTO IGNORE...` statement.  See my first comment as an example.

Edit: upon further investigation, this turns out to be a TiDB (5.7.25-TiDB-v5.1.0) problem. Oops. I'll try submit a TiDB issue instead.

**Comment by methane** [comment]
PyMySQL do not fetch warning message silently anymore.

**Comment by methane** [comment]
See #774. It is off since v0.10.0. No way to turn it on.
