### ISSUE TITLE
My Bug: Thanks You PyMySQL Team

### ISSUE THREAD

**Issue by alimp5** [PyMySQL/PyMySQL#1069]
Greetings!

I don't want to submit a bug/issue.
I just want to thank you 🥇PyMySQL🥇  team (all members/contributors).
Thanks for developing this open source project.

have great times in your life & works.

I'm sorry for opening this type of issue 👍🥇

**Comment by gabn88** [comment]
I also want to say thank you! 

My hosting does not give my sudo rights and due to a problem with homebrew mysqlclient could not be installed using pip. I have to wait till Monday before they install the required packages (using sudo apt-get). So I installed PyMySQL, which was a breeze, and in that way was able to get my server back to life again.
