### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by vladimirtiukhtin** [PyMySQL/PyMySQL#1105]
**Describe the bug**
I am getting `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate` despite certificates being issued properly

**To Reproduce**
If I set only `ssl_ca` - everything works, even hostname validation. However if I explicitly add `ssl_verify_cert` and `ssl_verify_identity` I get the message above

**Environment**
 - OS: Linux
 - Server and version: MariaDB 10.11
 - PyMySQL version: 1.0.3

**Comment by methane** [comment]
This error is come from OpenSSL.
Maybe, your server certivicate can not be verified with yoru `ssl_ca`.
But I don't know sure. It's your environment issue, not this project.

**Comment by vladimirtiukhtin** [comment]
Hi @methane. I can verify certificate using openssl. Also as I pointed above, only adding extra parameters cause the error

**Comment by methane** [comment]
If you think it's this project issue, please provide "complete step to reproduce" with Docker MySQL.

**Comment by vladimirtiukhtin** [comment]
> Without "extra parameter", PyMySQL don't verify server cert so verify error never happen

Yes, it does. I've proven that by intentionally applying "bad" certificate 

My server is right set up. Other clients work. I pointed to an error but you are just being rude. I may work with somebody else from the project and provide complete examples

**Comment by methane** [comment]
> My server is right set up. Other clients work.

”Other clients work" doesn't prove "right set up", because other clients may not verify certs.

> I pointed to an error but you are just being rude

Errors are not issue of project, unless it is confirmed that error must not happen in the situation.

And "Please provide complete step to reproduce" is not rude.
I can not log your environment in and your issue report doesn't contain enough information that prove your error is an issue of this project.
