### ISSUE TITLE
`pymysql.connect` should provide structured information about why the connection failed.

### ISSUE THREAD

**Issue by tomprince** [PyMySQL/PyMySQL#274]
I'd like to be able to determine if the connection request failed due to a network error, an authentication error, or something else.

**Comment by eevee** [comment]
Note that this happens even if the underlying problem is already a pymysql error — for example, if you try to connect to a database that doesn't exist, pymysql will throw the correct server error, then wrap it in an `OperationalError`.

I would suggest changing https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L842 to:

1. Only wrap the error if it's _not_ already a pymysql error.
2. If the error must be wrapped, include the original exception object as an attribute _and preserve the traceback_.

**Comment by tomprince** [comment]
The linked commit only address point (1) in @eevee's comment, not point (2).

**Comment by methane** [comment]
You can see original traceback in Python 3 without any modification.

I hate "preserve the stacktrace" in Python 2/3 compatible code.  It's very dark magic.
I don't want to introduce dependency to `six` module only for this.

I'll just add `tracekback.format_exc()` to exception message on Python 2.

**Comment by methane** [comment]
Does #304 seems OK?

**Comment by eevee** [comment]
It'd need to save the original exception, too — imagine it's a `socket.error` and calling code wants to handle a particular kind of socket error specially.

**Comment by methane** [comment]
@eevee I've added `original_exception` attribute, too.

**Comment by eevee** [comment]
Sounds great to me.  :ship: :it:  :)
