### ISSUE TITLE
fetchmany should return empty list instead of None

### ISSUE THREAD

**Issue by jettify** [PyMySQL/PyMySQL#284]
In current implementation `fetchmany` returns `None`, if there are no available rows, but according to PEP-249 
> An empty sequence is returned when no more rows are available. 

https://www.python.org/dev/peps/pep-0249/#fetchmany

And in other hand ``fetchmany`` in ``SSCursor`` returns empty list...

Is this intended behavior or a bug? In the latter case, I can make PR with fix.

**Comment by methane** [comment]
Thanks.  It is a bug.
MySQLdb1 returns empty tuple.  PyMySQL should have same behavior.
I'll fix it.

**Comment by jettify** [comment]
I think `fetchall` should have same behavior in order to maintain consistency.

**Comment by zzzeek** [comment]
This probably needs to be this way because its what MySQL-Python does, though in the bigger sense I think its wrong.   If you executed a statement that does not return a **result** (noting that an empty result is *still a result*), it is not appropriate to call fetchone(), fetchmany(), or fetchall().  An exception should be raised.

 Pep-249 is referring to the empty sequence "when no more rows are available", in the context of "the next set of rows of a query result".  In the case of a statement like "CREATE TABLE", there is no result.   

psycopg2 illustrates the appropriate behavior:

	>>> import psycopg2
	>>> conn = psycopg2.connect(user='scott', password='tiger', database='test', host='localhost')
	>>> cursor = conn.cursor()
	>>> cursor.execute("create table foo (id integer)")
	>>> cursor.fetchall()
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	psycopg2.ProgrammingError: no results to fetch
	>>>

**Comment by zzzeek** [comment]
sqlite3 is also returning the empty list.   pep-249 is ambiguous in so many ways....

**Comment by zzzeek** [comment]
in fact this is definitely wrong.  Let's read pep-249 [further](https://www.python.org/dev/peps/pep-0249/#fetchmany):

>  An Error (or subclass) exception is raised if the previous call to .execute*() did not produce any result set or no call was issued yet. 

therefore, calling fetchmany(), fetchall() or fetchone() should be raising here, not retunring None.

**Comment by zzzeek** [comment]
i see mysqldb obviously returns the tuple, and we want to copy them, so I'll close.   But this is not pep-249 behavior.
