### ISSUE TITLE
[RFC] Can I change license from MIT to GPL?

### ISSUE THREAD

**Issue by methane** [PyMySQL/PyMySQL#337]
See and discuss here https://groups.google.com/forum/#!topic/pymysql-users/xuF5p3vq8go

**Comment by grooverdan** [comment]
I don't think you are in violation for reading other implementations. Licensing only covers copyright and hence implementation but not concepts. (from disclaimers import not_a_laywer).

Changing license when a project like this has many contributors can be morally problematic.

LGPL maybe an option for error messages if that is still needed https://github.com/MariaDB/mariadb-connector-c/blob/master/libmariadb/errors.c

**Comment by DanielOaks** [comment]
So long as you're not copying code from those projects, I don't think it should be an issue. Generally you can read up and see how the interface works, and then implement that interface in your own code and it should be fine. (also not a lawyer).

The problem is that, I dunno about other people, but I'm already using this in some other projects that are not GPL. One of the main reasons I use this project is because of the permissive license, and that I could actually use it with my stuff, unlike MySQL-python. If the license on this project is changed to GPL, I unfortunately wouldn't be able to use it anymore, and there may be others in the same boat.

Changing the project license like this should be thought about very carefully. I know I'd need to jump to a fork that keeps the permissive license, or else maintain / keep using the old one 'til I was able to move to something else.

**Comment by grooverdan** [comment]
could LGPL package the error messages separately if that's the remaining motivation for change. Agree with@DanielOaks, a more restrictive license does reduce usability.

**Comment by methane** [comment]
OK, I'll not change the license.

But Google loses in case of Java copyright.
Definitions are protected by copyright as it's implementation.

It means something relating to protocol (e.g. COMMAND constant table) may be protected by copyright.
Copyright always cause me pain.  I hope Oracle won't sue me with the court.
