### ISSUE TITLE
Cannot store subclasses of types specified in converters.py's encoders dict

### ISSUE THREAD

**Issue by grantwwu** [PyMySQL/PyMySQL#348]
In converters.py, escape_item picks an escaping function using the encoders dict which maps types to functions.  Unfortunately, this does not work for subclasses of these types, because `instanceof(foo, fooclass)` does not necessarily imply that `type(foo) == fooclass`.  This breaks, for example, subclasses of datetime used to support dates below 1900.

(I'm kind of new to GitHub.  How would I create a pull request linked to this issue?)

**Comment by Naddiseo** [comment]
:+1: Just ran into this mysql. I'm resorting to monkey patching.

**Comment by methane** [comment]
You can add converter function to conv mapping.
You can convert your data into string before passing it to cursor.execute(), too.

**Comment by methane** [comment]
Checking isinstance() for all classes in converter dict may make PyMySQL too slow.

**Comment by Naddiseo** [comment]
> You can add converter function to conv mapping.
> You can convert your data into string before passing it to cursor.execute(), too.
That's very inconvenient when the `cursor.execute` is wrapped in an ORM (django/sqlalchemy), and also would mean I need to change my entire codebase when switching between pymysql and psycopg for backends. 
> Checking isinstance() for all classes in converter dict may make PyMySQL too slow.
It only needs to be done when the value type isn't found in the mapping, so it's only slower for values whose type isn't in the dictionary (which in most use-cases will be rare).

My current usecase is a custom `Enum` class, which is stored as an int in the database, but in the code is passed around as the actual enum. Adding the base class `Enum` to the mapping dictionary wont work because of the `type(val)` check, which will then pass the value through the string converter. However, calling `str(enum_value)` returns the label of the enum, not the integer ordinal value. 

I monkey patched `escape_item` so that it looks something like the following, which seemed to work:

```python
def escape_item(val, charset, mapping=None):
    if mapping is None:
        mapping = encoders
    encoder = mapping.get(type(val))
    
    if not encoder:
        # only do the slow path if mapping isn't found
        for tp, enc in mapping.items():
            if isinstance(val, tp):
                encoder = enc
                break

    # Fallback to default when no encoder found
    if not encoder:
        try:
            encoder = mapping[text_type]
        except KeyError:
            raise TypeError("no default type converter defined")

    if encoder in (escape_dict, escape_sequence):
        val = encoder(val, charset, mapping)
    else:
        val = encoder(val, mapping)
    return val

```

**Comment by methane** [comment]
I use SQLAlchemy and it provides way to support custom types.

While I don't use Django, I believe Django support custom type too.
It's very basic feature for ORMs.

**Comment by methane** [comment]
I found: https://docs.djangoproject.com/en/1.8/howto/custom-model-fields/#custom-database-types

**Comment by Naddiseo** [comment]
Let me see if I can explain better by giving a more detailed description of my particular use case.

I have an enum class which has int and str conversions:
```python
from myenum in Enum

class BaseEnum(Enum):
    def __int__(self):
        return self.value
    def __str__(self):
        return self.name

class EnumA(BaseEnum):
    A = 1
    B = 2

>> int(EnumA.A)
1
>> str(EnumA.A)
'A'
```
And a custom (django) model field which internal stores the enum as an int:
```python
class EnumField(models.IntegerField):
    def get_internal_type(self):
        return 'IntegerField' # cause django and aldjemy to treat these fields as int fields
    # stuff that converts enum <-> int

class MyModel(models.Model):
    enum_value = EnumField(EnumA)
```
Django will correctly convert the values so that the back always receives the int value:
```python
>>> MyModel.objects.filter(enum_value = EnumA.A).query
'SELECT * FROM models_mymodel WHERE enum_value = 1'
```

This isn't a custom database type, 
Now, here's comes (one of) my problems): django's ORM sucks for certain things (like left joins with more than one condition).
So, instead of using raw sql, I'm using sqlalchemy to do some of the more complex queries (using the right tool for the job). To do this I'm using https://github.com/Deepwalker/aldjemy which hooks the django models into sqlalchemy. (Please ignore the issue of mixing the two ORMs, and using aldjemy, it's not relevant to this argument.)
Now I can use sqlalechemy with django:
```python
>>> MyModel.sa.query(MyModel.sa.enum_value == EnumA.A)
# Some error, cannot adapt enum values
```

Now, with psycopg2 as the backend I can add an adapter for my enum classes:
```python
import psycopg2
from psycopg2.extensions import adapt
psycopg2.extensions.register_adapter(BaseEnum, lambda x: adapt(int(x)))
>>> MyModel.sa.query(MyModel.sa.enum_value == EnumA.A)
# WORKS!
```

But, when I have pymysql as the backend, what is the equivilent? I see two possible solutions: 
1) Since I'm not as familiar with sqlalchemy as I am with django, there could be something on its level that would allow me to adapt all subclasses of `BaseEnum`. (Do you know of one?)
2) Tell pymysql to adapt all subclasses of `BaseEnum` the same way psycopg2 does.

Solutions that wont work:
1) calling `int` on every enum value in my code. It's a band-aid solution.
2) Changing my model/field definitions. Again, fixing this issue in my code is a band-aid solution to accommodate a deficiency at another level.  

Now, back on topic for this issue: although my particular use case can be solved a different way, it doesn't negate the fact that pymysql doesn't support adapting types which derive from a common base; it's sort of a feature parity with another backend so that switching backends can be seemless.

**Comment by methane** [comment]
@Naddiseo What "band-aid solution" means?

Solving app layer problem in protocol layer is bad idea.
Converter in connection object is for mapping low level types.  For example, you can use decimal.Decimal instead of float for MySQL's  double.
@grantwwu's problem should be solved there.  But your problem seems higher level.

If you want to switch backends, you should rely on only APIs defined on DB-API 2.0.
There are some major RDBMS and many drivers for them.
psycopg2 and PyMySQL are just two of them.

> 1) Since I'm not as familiar with sqlalchemy as I am with django, there could be something on its level that would allow me to adapt all subclasses of BaseEnum. (Do you know of one?)

TypeDecorator can.  It can be type-safe (raise TypeError when int is passed for enum column).

I've wrote example for support Enum by TypeDecorator.   http://qiita.com/methane/items/dd19bc7be27a5e991cca
(It is Japanese article, but example code may help you).
