### ISSUE TITLE
Feature Request: MySQL login path support

### ISSUE THREAD

**Issue by seagoj** [PyMySQL/PyMySQL#362]
I was hoping you'd consider adding login via --login-path. This would allow for PyMySQL to make connections via encrypted connection information in the ~/.mylogin.cnf file.

Because of the encryption, I think you would have to pass the parameter all the way down to the mysql client, which may not even be possible, but it would be a nice feature.

[Documentation](http://dev.mysql.com/doc/mysql-utilities/1.5/en/mysql-utils-intro-connspec-mylogin.cnf.html)

Thanks

**Comment by methane** [comment]
I can't find format spec of mylogin.cnf.
I read the mysql client and found it uses AES128 for encryption.
It means it requires additional dependency for encryption libraries.
I'll consider about this after 0.7.

**Comment by tsroten** [comment]
@methane Here is the implementation that mycli uses to read the login path file.

**Comment by ngaitanis** [comment]
Has there been any action on this? Perhaps an estimate on when/if this will be implemented?

**Comment by methane** [comment]
No action, and no estimate.

**Comment by simnim** [comment]
This feature is super useful and would be great for security.
I hope it gets more attention.

**Comment by methane** [comment]
> This feature is super useful and would be great for security.

NO!  The format put key and lock in one place.  All attacker can decrypt it.
It's not safer than plaintext from attacker's point of view.
It can even dangerous if people think it improve security.

I don't think it's useful.  But I know there are people feel it's useful.
I'll accept the feature if it:

* is consistent with MySQL Connector/C
* doesn't slowdown making new connection
* well tested, and easy to maintain (I never use it, contributors should maintain it)

**Comment by simnim** [comment]
> NO! The format put key and lock in one place. All attacker can decrypt it.

Ok, maybe great was the wrong word, but I think "NO!" is too strong a reaction.

The encryption is shit, it's true, but that's mostly irrelevant.

I'm not trying to start a flamewar or anything, I just think there are valid reasons why it can be good for security. Mainly that you don't store passwords in your repo and you can put them in locked down locations etc.

Besides, how is it any better than `~/.ssh/id_rsa`? (I know you can add a password to it, but usually people don't for programmatic scp and such.)

Checking code into a repo that looks like this is arguably much worse.
```
# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd',
                             db='db',
                             charset='utf8mb4',
                             cursorclass=pymysql.cursors.DictCursor)
```

I'm not sure how one would do a better job on non-interractive programmatic access security. Maybe with an additional password (that'll go right into a keychain file and probably be accessible to a hacker anyway.) I don't pretend to be a security expert, I'm really not, but I don't feel like it's better to add code like the above to a repo than a file path to a locked down file outside the repo that's invisible to git and can be revoked, cycled, etc at the users desired level of paranoia.

**Comment by keithjjones** [comment]
👍 I think it would be useful.

**Comment by vr001** [comment]
Yeah, this would be a cool feature to have. Surprised how its still open !

**Comment by methane** [comment]
> Ok, maybe great was the wrong word, but I think "NO!" is too strong a reaction.

I use strong word because many people misunderstood how my_login is good for.

In case of MySQL cli, `mysql -u username -ppassword` is very weak.  Any user can show the password.
You can use `mysql -u username -p` for interactive use.  But it can't be used in non interactive shell script.
So you must put password somewhere in the file, in the safe directly.  That's why `~/mylogin.cnf` is added.

AES encryption doesn't contribute to security.  It's only for "fool proof".

In case of Python and PyMySQL, it is programming language, not just a command.
So you can read secret from any path you can set up, outside of repo.

In other words; `mysql -p$(cat /path/to/safe/mypassword)` is dangerous.  But following is safe.

```py
with open('/path/to/safe/mypassword') as f:   # This file must not read by other users. (e.g. chown o-r)
    secret = f.read()
conn = pymysql.connect(user="myuser", password=secret), ...)
```

That's why direct support of my_login is not so important than command line programs like mysql or mysqldump.

---

I agree that supporting it is "convenient", and "fool proof" is nice to have for security.

But I don't want to add dependency to this project.
And I'm very close to burn-out about these projects.  I must keep project small, maintainable.

On the other hand, you can write your own library to read `my_login.cnf`, or other tools for managing secrets with fool proof.
And it is better than reading `my_login.cnf` and decrypt everytime when creating new connection for performance.

That's why I don't have any plan to support it.
I hope there is de-facto / recommended / standard RSA and AES library for Python, which can be used on even GAE/Python Standard, and GPL free.

Please don't say "+1" or other message like them and send spam mail to me.
Next time, I close and lock this issue.
(I watching all repositories to check real, important issues.  But I receive dozen spam mails from free riders).

**Comment by simnim** [comment]
methane,
I appreciate all the hard work you've put in. 
That all makes sense and I retract my support for this.

I think it's fair to close the issue and just say use plaintext + chmod 600.

Thanks,
-Nick

**Comment by methane** [comment]
I decided to not implement this to avoid increasing complexity and maintenance cost.
I lost motivation to grow this project already.

Instead, I've released [myloginpath](https://pypi.org/project/myloginpath/).
You can use it to read login path file.
