### ISSUE TITLE
issue with host string ?

### ISSUE THREAD

**Issue by cellinho** [PyMySQL/PyMySQL#469]
i got this error since 1 month ago.
help!

`connection = pymysql.connect(host='192.168.33.14', user='root',password='',  db='csgo')`

when i run the app by `python app.py`

it says `pymysql.err.InternalError: (1130, "Host '192.168.33.1' is not allowed to connect to this MySQL server")`

at first i though i was coding wrong. but look at the error ip its not 192.168.33.14 that i put.
whats going on ?

**Comment by methane** [comment]
**Don't use github issue tracker for asking general question!!**

OSS maintainers pays massive efforts to check issues to increase software quality.
Using issue tracker as Q&A site cause maintainer’s burnout.

Go Stackoverflow or user's ML (python-list or PyMySQL-users).  Many users can support each other instead of one OSS maintainer.  It's scalable community.

**Comment by cellinho** [comment]
well, i was wrong but I'm not asking a general question. as you can see i've got a error that says 
ip do not match with the ip that i put on host=''.

**Comment by methane** [comment]
I know what the error message means.  I can reproduce the error without Python.
It's very very general problem.  You misconfigured MySQL.

Every MySQL admins know the message.
If you were googled enough, you must fixed the problem by yourself.

**Comment by methane** [comment]
Google: "MySQL Error 1130".

Issue tracker is not place to teach how to google.
