### ISSUE TITLE
[TASK] Use docker to setup MySQL 5.1 and 5.7 on Travis-CI.

### ISSUE THREAD

**Issue by birm** [PyMySQL/PyMySQL#494]

**Comment by grooverdan** [comment]
example of a project using docker on mysql server instances https://github.com/MariaDB/mariadb-connector-c

**Comment by methane** [comment]
I already do this on PyMySQL/mysqlclient-python.
No example is needed.  Only actual effort (time and energy) is needed for it.

**Comment by grooverdan** [comment]
Apologises. Should of looked more. I'll give some time/effort for 5.5+ docker tests.

5.1 seems possible with https://downloads.mysql.com/archives/get/file/mysql-5.1.72-linux-x86_64-glibc23.tar.gz on Ubuntu truty.

**Comment by grooverdan** [comment]
Before I go too far correcting MySQL-5.1 errors, do you still want MySQL-5.1 supported?

Failing test test_cleanup_rows_unbuffered had 7(?) outstanding packets.

WIP: https://travis-ci.org/grooverdan/PyMySQL/builds/371411404
https://github.com/grooverdan/PyMySQL/tree/travis-mysql-5.1

**Comment by methane** [comment]
I hadn't test with MySQL 5.1 for a long time.
Is it possible to test it easily with Docker?
I don't want to maintain custom, long shell script for MySQL 5.1.
I know almost nothing about shell script.

**Comment by grooverdan** [comment]
Unofficial docker images can be used (https://travis-ci.org/grooverdan/PyMySQL/jobs/372307130), with no additional shell script (https://github.com/grooverdan/PyMySQL/commit/0350ed427ab2219bad9b8050f47c86950c62cb35). I'll submit this after I fix the `ERROR: test_cleanup_rows_unbuffered (pymysql.tests.test_cursor.CursorTest)`.

MySQL-5.1 has been "EOL (end of life) by Oracle since December 31, 2013 (https://www.mysql.com/support/eol-notice.html). "Oracle Lifetime Sustaining Support" == "No new releases, no new fixes (no error correction for new issues), no new updates. " (https://www.mysql.com/support/).

5.1.73 is still in Centos-6/RHEL-6, which is getting maintenance updates until product retirement November 30th, 2020 (https://access.redhat.com/support/policy/updates/errata/#Life_Cycle_Dates). I think this should be the date to drop MySQL-5.1 support from PyMySQL. Yes/No?

**Comment by methane** [comment]
> I think this should be the date to drop MySQL-5.1 support from PyMySQL. Yes/No?

OK, let's drop it instead of using unofficial docker image.
Thanks.

**Comment by grooverdan** [comment]
The unofficial image chosen does reasonable things to package for docker the last official tarball https://hub.docker.com/r/mtirsel/mysql-5.1/~/dockerfile/. Its almost identical to the official ones from later versions https://github.com/docker-library/mysql/blob/2e4f2224f31e101d07c1e6a7c0da8245fde725c9/8.0/Dockerfile.

I'll remove the MySQL-5.1 docker image for now.
