### ISSUE TITLE
connect() resolves hostname - access denied

### ISSUE THREAD

**Issue by BirknerAlex** [PyMySQL/PyMySQL#509]
If I connect with host="localhost" the connection should be created with hostname "localhost". But it seems the library resolves the hostname to the local IPv6 address: ::1

I always get the error: Access denied for user 'root'@'::1' (using password: YES) 

The password is only set for host "localhost" and not for 127.0.0.1 or ::1. No connection is and should be possible via 127.0.0.1 and ::1.

The MySQL cli client does respect the hostname:

```
[root@dev001 ~]# mysql -hlocalhost -p123456
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 20195
Server version: 5.6.32 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> exit
Bye
[root@dev001 ~]# mysql -h127.0.0.1 -p123456
ERROR 1045 (28000): Access denied for user 'root'@'127.0.0.1' (using password: YES)
```

## Executable script to reproduce (for bugs)

code:
```python
import pymysql

# Connect to the database
connection = pymysql.connect(host='localhost',
                             user='user',
                             password='passwd',
                             cursorclass=pymysql.cursors.DictCursor)
```

**Comment by methane** [comment]
[Read this article carefully](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.hdf6lpk11)

**Comment by BirknerAlex** [comment]
This wasn't really a question, it's a simple bug report. It seems like your library has a bug in the connection handling. MySQL needs to know which hostname connects because you can create different credentials for one user for each hostname.

And If I provide "localhost" as hostname the library connection with hostname ::1 instead of localhost. This causes issues and wrong password exceptions.

**Comment by methane** [comment]
Are you really read the article???

> Q. I don’t know is this a bug or my usage is wrong
>
> A. Until you have confidence it’s a bug, it’s a question, not a bug report.
> Ask in forum, and if it seems bug after discussion, file a bug report to
> issue tracker with URL and summary of the discussion.

**Comment by methane** [comment]
Actually speaking, this is not a bug but a limitation.  Your estimation is wrong because no one
can connect without resolving.

https://dev.mysql.com/doc/refman/5.5/en/connecting.html

> On Unix, MySQL programs treat the host name localhost specially, in a way that is likely different from what you expect compared to other network-based programs. For connections to localhost, MySQL programs attempt to connect to the local server by using a Unix socket file. This occurs even if a --port or -P option is given to specify a port number. 

Since PyMySQL doesn't know where unix socket is, PyMySQL can't emulate such a special behavior.
You must send `unix_socket` option explicitly.

And this special behavior is very common pitfall.  Every MySQL experts know about this.

https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.xb6aegb1p

> Stackoverflow is designed to polish questions and answers. Polished questions and answers are reusable knowledge. If there are many knowledge in the StackOverflow, many users can solve their problem by Googling.

If you post this question in Stackoverflow, (1) one of many MySQL experts can answer instead of
PyMySQL author (only one in this world), and (2) many others can solve their issue by googling.

Please read the article **carefully**.

**Comment by bnoreus** [comment]
Hi,

I'm having similar issues with endpoint resolution. I'm using your driver on a program on AWS. I'm trying to connect to an AWS endpoint "database.xxxxxx.eu-west-1.rds.amazonaws.com" but it resolved the endpoint to the local private IP instead of resolving the endpoint to the correct IP. The PHP driver and MySQL client have no issues connecting to the AWS endpoint.

**Comment by kieran-lemayai** [comment]
As someone trying to resolve this exact same issue, two years later...no, no it's not easily resolvable by Googling. I'm not pleased to see the maintainer acting like an arrogant dick either. Two years late, but I can't let this kind of thing pass; this kind of condescending crap happens way too often from hopped-up maintainers.

He's also not wrong. This has nothing to do with whether an IP connection or Unix socket is used, and everything to do with how permissions are resolved, as his examples clearly stated. Did you read the issue *carefully*?

To anyone else who stumbles across this, if you want a real answer: the problem probably lies elsewhere in your configuration. Check that you are connecting to the correct port and host. Check that the same username/password configuration is being used both with the command line client and the Python code. Check whether the Python code works directly from the command line. All those neat things.

**Comment by methane** [comment]
> As someone trying to resolve this exact same issue, two years later...no, no it's not easily resolvable by Googling.

There is MySQL slack community, or Stackoverflow.

> I'm not pleased to see the maintainer acting like an arrogant dick either.

I'm very frustrated people treat maintainer as free tech support, instead of using community for asking question.

> He's also not wrong.

He is wrong.  If there are little network knowledge, "the connection should be created with hostname "localhost". But it seems the library resolves the hostname to the local IPv6 address: ::1" is nonsense.

>  This has nothing to do with whether an IP connection or Unix socket is used, and everything to do with how permissions are resolved, as his examples clearly stated.

I don't understand your English.

> Did you read the issue _carefully_?

And I already replied the answer in https://github.com/PyMySQL/PyMySQL/issues/509#issuecomment-244072354.
Did you the reply _carefully_?

"localhost" in MySQL permission means "unix domain socket".
That is very common pitfall every MySQL DB admins knows.
No need to bother OSS maintainer.

**Comment by kieran-lemayai** [comment]
*If you are not willing to be bothered, stop being a maintainer.* Hell, I'll take it off your hands, because this kind of arrogance needs to be culled.

When someone comes to you with an innocent question and doesn't know what they are doing, you don't get to reply to them as a condescending ass. You assumed what the issue was and dismissed it out of hand without asking any questions. It's disrespectful, and it's an insult to the people who are trying to be respectful of *your* expertise. Not having that expertise, we have *no choice* but to ask these questions when we come up against a wall.

I suggest you look at how the *professionally-run* repositories handle this. I understand your frustrations, but it doesn't give you leeway to be rude. Flag it as a non-issue, close it, and move on. Github issues are not a place to ask questions; but neither are they a place to screech about your ideals.

**Comment by methane** [comment]
> Not having that expertise, we have _no choice_ but to ask these questions when we come up against a wall.

No need to ask to OSS maintainer.  You can use communities without bothering maintainer.

> Flag it as a non-issue, close it, and move on.

I did it again and again.  And I get email notifications from closed issue again and again, like this time.
There are many noise in GitHub notifications.  But I can not stop reading it, because
I don't want to miss real issues.

Only I can is lock the issue.  I'll do it for now.
