### ISSUE TITLE
expose more methods

### ISSUE THREAD

**Issue by bingtel** [PyMySQL/PyMySQL#538]
Hi, i am trying to implement a activerecord orm with pymysql and i want to get the metadata of the tables . I think **MySQLResult** can contribute to this. But methods of **MySQLResult** are prefixed with '_'. 

I think more classes and public methods should be exposed to users.

**Comment by methane** [comment]
I don't want to add public stable APIs.
More public stable APIs makes it difficult to future refactoring or optimization.

More generally speaking, if you think DB-API 2.0 doesn't provide enough information
for ORMs, you should ask a question to [DB-SIG](https://mail.python.org/mailman/listinfo/db-sig).

If you hope PyMySQL add public stable API, you should provide:

* Concrete and realistic example which describe why the API is good for many users (not only for you).
* Reason why the API should be provided by only PyMySQL, instead of adding it to DB-API 2.0

Without enough reason I can agree, I'll never add public API.

**Comment by methane** [comment]
BTW, SQLAlchemy and PeeWee can use PyMySQL without accessing MySQLResult.
You should read how they use PyMySQL before asking adding API.
