### ISSUE TITLE
pymysql.err.InternalError: Packet sequence number wrong

### ISSUE THREAD

**Issue by jacobet** [PyMySQL/PyMySQL#622]
Hi,
I read similar problems but I didn't success to solve my problem, so.. here is my code, only that.

import pymysql

hostname = 'freehosting.host'
port = 1234
username = 'username'
password = 'pass'
database = 'mydb'

myConnection = pymysql.connect(host = hostname, user = username, passwd = password, db = database, port = port)
print "Using pymysql..."
myConnection.close()

I got an error - 
    myConnection = pymysql.connect(host = hostname, user = username, passwd = password, db = database, port = port)
  File "C:\Program Files\Python27\lib\site-packages\pymysql\__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "C:\Program Files\Python27\lib\site-packages\pymysql\connections.py", line 706, in __init__
    self.connect()
  File "C:\Program Files\Python27\lib\site-packages\pymysql\connections.py", line 931, in connect
    self._get_server_information()
  File "C:\Program Files\Python27\lib\site-packages\pymysql\connections.py", line 1245, in _get_server_information
    packet = self._read_packet()
  File "C:\Program Files\Python27\lib\site-packages\pymysql\connections.py", line 1001, in _read_packet
    % (packet_number, self._next_seq_id))
pymysql.err.InternalError: Packet sequence number wrong - got 80 expected 0

Someone wrote here about  multiple threads (#[138](https://github.com/noplay/python-mysql-replication/issues/138) ). I don't understand how and why

**Comment by methane** [comment]
In your case, it seems not relating to multiple threads.
But I don't know what is your environment.
Information about complete step to reproduce is required.

**Comment by jacobet** [comment]
What do you mean? It's python 2.7

**Comment by methane** [comment]
I meant I can't reproduce your issue by just reading your report.
Your report have too few information and I can't distinguish it's your environment issue
or PyMySQL's bug.

And I don't have motivation to support you to write good issue report.
OSS maintainers are not free tech support.
Please go some MySQL forum.

**Comment by methane** [comment]
The error means just one sort of protocol error.
There are many possibilities and wrong multi threading is just on of them.
For example, if you connect to HTTP server from PyMySQL, same (or similar) error will be happen.
And I don't know what's `host = 'freehosting.host'`.  I don't know even it is MySQL? HTTP? SMTP?
Such issue reports are just noise for me.

"Complete step to reproduce" means "Complete step to reproduce your issue in clean VM",
from installing MySQL and Python into clean VM".

**Comment by jacobet** [comment]
I'm really sorry.. it is MySQL

**Comment by methane** [comment]
"It is MySQL" is not enough information to reproduce.
**"Complete step to reproduce your issue in clean VM", from installing MySQL and Python into clean VM".**

**Comment by jacobet** [comment]
What do you need more? I'm sorry but I have no experience with VM..

**Comment by methane** [comment]
Sorry, but I don't want to be free tech support.
Please go stackoverflow or elsewhere.

**Comment by woods-chen** [comment]
@methane Hi methane, I got the same error.
 I use single thread, and following is my code:

import pandas as pd
import pymysql
conn = pymysql.connect(host='mysql_ip_address', port=3306, user='user', passwd='passwd', db='test')
sql = 'select * from test;'
data = pd.read_sql(sql, conn)

then I will get pymysql.err.InternalError or pymysql.err.InterfaceError sometimes.
and this error is not easy to reproduce because it doesn't raise error frequently.
so is it possibly related to the network error or something about pandas ?

I use mysql as sql server and pymysql version 0.9.2, python version 3.6.5.

**Comment by methane** [comment]
>  I got the same error.

It may be not same error.  Same exception type doesn't mean same error.
Exactly same traceback means probably same error.

> I will get pymysql.err.InternalError or pymysql.err.InterfaceError sometimes.

Two error types?  It isn't this issue's error.

>  so is it possibly related to the network error or something about pandas ?

I don't know.  Too less information.  Why don't you paste full traceback?
OS and MySQL version is also important, as detailed as possible.

**Comment by woods-chen** [comment]
@methane thank you for your replying . some times I got pymysql.err.InternalError and sometime pymysql.err.InterfaceError with the same code.
and wait a moment for me to post full traceback, our server is not allowed to connect to the internet.

**Comment by woods-chen** [comment]
the Mysql version is 5.6, and OS is CentOS 6.9.
the error message is:
exception type: InterfaceError,
trace back: 

        "trace_back" : [ 
            "  File \"/mooc/test_statistics/test_statistics.py\", line 257, in <module>\n    test_statistics_update = pd.read_sql(sql_videotestlogb, engine_read).astype(fmt_table_target_testid).astype(fmt_table_target_score)\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py\", line 397, in read_sql\n    chunksize=chunksize)\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py\", line 1085, in read_query\n    result = self.execute(*args)\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py\", line 976, in execute\n    return self.connectable.execute(*args, **kwargs)\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 2075, in execute\n    return connection.execute(statement, *multiparams, **params)\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 942, in execute\n    return self._execute_text(object, multiparams, params)\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1104, in _execute_text\n    statement, parameters\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1200, in _execute_context\n    context)\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1406, in _handle_dbapi_exception\n    self._autorollback()\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py\", line 76, in __exit__\n    compat.reraise(type_, value, traceback)\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/compat.py\", line 187, in reraise\n    raise value\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1406, in _handle_dbapi_exception\n    self._autorollback()\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 827, in _autorollback\n    self._root._rollback_impl()\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 706, in _rollback_impl\n    self._handle_dbapi_exception(e, None, None, None, None)\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 1334, in _handle_dbapi_exception\n    exc_info\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/compat.py\", line 203, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/util/compat.py\", line 186, in reraise\n    raise value.with_traceback(tb)\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/engine/base.py\", line 704, in _rollback_impl\n    self.engine.dialect.do_rollback(self.connection)\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py\", line 1796, in do_rollback\n    dbapi_connection.rollback()\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/pymysql/connections.py\", line 431, in rollback\n    self._execute_command(COMMAND.COM_QUERY, \"ROLLBACK\")\n", 
            "  File \"/mooc/anaconda3/lib/python3.6/site-packages/pymysql/connections.py\", line 745, in _execute_command\n    raise err.InterfaceError(\"(0, '')\")\n"
        ]

**Comment by woods-chen** [comment]
and this is another error I got, the same script, and I use one single pymysql.connections.Connection object for querying data several times (not the same time, in a single thread).
and sorry for that I've got only part of the full trace back due to that I've delete the log, and can only get part of them from the picture I've taken. ( and there may be some typos because they are typed by hand).


  File "/mooc/anaconda3/lib/python3.6/site-packages/pynysql/connections .py", line 670, in _read_packet
    % (packet_number, self ._next_seq_id)) 
pymysql.err.InternalError: Packet sequence number wrong - got 2 expected I 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last) : 
  File "/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py", line 1404, in execute 
    self.con.rollback()
  File "/mooc/anaconda3/lib/python3.6/site-packages/pymysq1/connections.py", line 431, in rollback 
    self._execute_command(COMMAND.QUERY, "ROLLBACK") 
  File "/mooc/anaconda3/lib/python3.67site-packages/pymysql/connections.py", line 745, in _execute_command 
    raise err.InterfaceError("(0, '')") 
pymysqI.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred: 

Traceback (most recent call last) : 
  File "/mooc/test_statistics.py", line 293, in qnodule> 
    test_statistics_update = pd.read_sql(sql_videotestlogb, conn_read).astype(fmt table_target_testid).astype(fmt_table_target_score) 
  File "/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sqt.py", line 381, in read_sql 
    chunksize=chunksize) 
  File "/mooc/anaconda3/1ib/python3.6/site-packages/pandas/io/sql.py", line 1435, in read_query 
    cursor = self.execute(*args)
  File "/mooc/anaconda3/1ib/python3.6/site-packages/pandas/io/sq1.py", line 1408, in execute 
    raise_with_traceback(ex) 
  File U/?ooc/anaconda3/lib/python3.6/site-packages/pandas/compat/__init__.py", line 403. in raise_with traceback 
    raise exc.with_traceback(traceback) 
  File "/mooc/anaconda3/1ib/python3.6/site-packages/pandas/io/sq1.py", line 1404, in execute 
    self.con.rollback( ) 
  File "/mooc/anaconda3/1ib/python3.6/site-packages/pymysql/connections.py", line 431, in rollback 
    self._execute_command(COMMAND.COM_QUERY, "ROLL-BACK") 
  File "/mooc/anaconda3/lib/python3.67site-packages/pynysqt/connections.py", line 745, in _execute_comand 
    raise err. InterfaceError("(0, '')") 
pandas.io.sq1.DatabasError: Execution failed on sql:SELECT testid, score, COUNT(*) AS righttines 
                            FROM videotestlogb 
                            where id > O and id 40404935 
                            GROIUP BY testid, score; 
Packet sequence mmber wrong - got 2 expected 1

**Comment by woods-chen** [comment]
and this is another error I got, the same script, and I use one single pymysql.connections.Connection object for querying data several times (not the same time, in a single thread).
and sorry for that I've got only part of the full trace back due to that I've delete the log, and can only get part of them from the picture I've taken. ( and there may be some typos because they are typed by hand).

`File "/mooc/anaconda3/lib/python3.6/site-packages/pynysql/connections .py", line 670, in _read_packet
% (packet_number, self ._next_seq_id))
pymysql.err.InternalError: Packet sequence number wrong - got 2 expected I

During handling of the above exception, another exception occurred:

Traceback (most recent call last) :
File "/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py", line 1404, in execute
self.con.rollback()
File "/mooc/anaconda3/lib/python3.6/site-packages/pymysq1/connections.py", line 431, in rollback
self._execute_command(COMMAND.QUERY, "ROLLBACK")
File "/mooc/anaconda3/lib/python3.67site-packages/pymysql/connections.py", line 745, in _execute_command
raise err.InterfaceError("(0, '')")
pymysqI.err.InterfaceError: (0, '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last) :
File "/mooc/test_statistics.py", line 293, in qnodule>
test_statistics_update = pd.read_sql(sql_videotestlogb, conn_read).astype(fmt table_target_testid).astype(fmt_table_target_score)
File "/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sqt.py", line 381, in read_sql
chunksize=chunksize)
File "/mooc/anaconda3/1ib/python3.6/site-packages/pandas/io/sql.py", line 1435, in read_query
cursor = self.execute(args)
File "/mooc/anaconda3/1ib/python3.6/site-packages/pandas/io/sq1.py", line 1408, in execute
raise_with_traceback(ex)
File U/?ooc/anaconda3/lib/python3.6/site-packages/pandas/compat/init.py", line 403. in raise_with traceback
raise exc.with_traceback(traceback)
File "/mooc/anaconda3/1ib/python3.6/site-packages/pandas/io/sq1.py", line 1404, in execute
self.con.rollback( )
File "/mooc/anaconda3/1ib/python3.6/site-packages/pymysql/connections.py", line 431, in rollback
self._execute_command(COMMAND.COM_QUERY, "ROLL-BACK")
File "/mooc/anaconda3/lib/python3.67site-packages/pynysqt/connections.py", line 745, in _execute_comand
raise err. InterfaceError("(0, '')")
pandas.io.sq1.DatabasError: Execution failed on sql:SELECT testid, score, COUNT() AS righttines
FROM videotestlogb
where id > O and id 40404935
GROIUP BY testid, score;
Packet sequence mmber wrong - got 2 expected 1`

**Comment by methane** [comment]
You don't use thread, process, and gevent, right?

**Comment by woods-chen** [comment]
No, I'm quite sure, single process single thread, no gevent. 
however I use pandas to read sql data (pd.read_sql), and I'm not sure whether pandas use them or not.

**Comment by methane** [comment]
I don't use Panda.  Please read Panda document before asking question to me.
(Why I need to read Panda document for you?)

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html

```
con : SQLAlchemy connectable (engine/connection) or database string URI

    or DBAPI2 connection (fallback mode)

    Using SQLAlchemy makes it possible to use any DB supported by that library. If a DBAPI2 object, only sqlite3 is supported.
```

You must not pass the connection object to read_sql.

**Comment by woods-chen** [comment]
Thank you @methane, I tried to pass `SQLAlchemy engine` object to `pandas.read_sql` function several months ago, and it still got error sometimes, as I remember. However I can't find the error log any more.  Now I'm going to try sqlalchemy (mysql+pymysql for create_engine) again, and I will tell you then if it gets error again. Thank you.

**Comment by methane** [comment]
What is panda version?

**Comment by woods-chen** [comment]
pandas 0.23.0

**Comment by methane** [comment]
```
File "/mooc/anaconda3/lib/python3.6/site-packages/pynysql/connections .py", line 670, in _read_packet
% (packet_number, self ._next_seq_id))
pymysql.err.InternalError: Packet sequence number wrong - got 2 expected I
```

There are no log before this?

**Comment by methane** [comment]
Logs after "During handling of the above exception, another exception occurred:" is less useful.
Write full traceback before this message.

**Comment by woods-chen** [comment]
The logs before are deleted, and what I posted is from a picture that someone sent to me (the corresponding script is run by crontab).
Following is the new error log I got. However the corresponding python script is run by a frame called jiacrontab (written with go lang, see https://github.com/iwannay/jiacrontab), I'm not sure it use multi thread or not. and the stdout is redirected by this frame , flowing log if copied from this frame.

    Traceback (most recent call last):
    File "/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py", line 1400, in execute
    cur.execute(*args)
    File "/mooc/anaconda3/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
    File "/mooc/anaconda3/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
    File "/mooc/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 516, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    File "/mooc/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 727, in _read_query_result
    result.read()
    File "/mooc/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 1073, in read
    self._read_result_packet(first_packet)
    File "/mooc/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 1143, in _read_result_packet
    self._read_rowdata_packet()
    self._read_rowdata_packet()
    File "/mooc/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 1177, in _read_rowdata_packet
    packet = self.connection._read_packet()
    File "/mooc/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 670, in _read_packet
    % (packet_number, self._next_seq_id))
    pymysql.err.InternalError: Packet sequence number wrong - got 2 expected 180

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py", line 1404, in execute
    self.con.rollback()
    File "/mooc/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 431, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
    File "/mooc/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
    pymysql.err.InterfaceError: (0, '')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
    File "/mooc/blacklist/blacklist_filter_release.py", line 186, in <module>
    data_py = fetch_data_py(conn_read)
    File "/mooc/blacklist/blacklist_filter_release.py", line 15, in inner
    res = func(*args, **kargs)
    File "/mooc/blacklist/blacklist_filter_release.py", line 130, in fetch_data_py
    data = pd.read_sql(sql, conn)
    File "/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py", line 381, in read_sql
    chunksize=chunksize)
    File "/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py", line 1435, in read_query
    cursor = self.execute(*args)
    File "/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py", line 1408, in execute
    raise_with_traceback(ex)
    File "/mooc/anaconda3/lib/python3.6/site-packages/pandas/compat/__init__.py", line 403, in raise_with_traceback
    raise exc.with_traceback(traceback)
    File "/mooc/anaconda3/lib/python3.6/site-packages/pandas/io/sql.py", line 1404, in execute
    self.con.rollback()
    File "/mooc/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 431, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
    File "/mooc/anaconda3/lib/python3.6/site-packages/pymysql/connections.py", line 745, in _execute_command
    raise err.InterfaceError("(0, '')")
    pandas.io.sql.DatabaseError: Execution failed on sql: SELECT c.eid,
    c.channelid,
    c.title,
    t.content
    FROM mooc_db.`comment` c
    LEFT JOIN mooc_db.`comment_content` t
    ON c.commentuuid = t.commentuuid
    WHERE c.is_station = 0;
    Packet sequence number wrong - got 2 expected 180
    unable to rollback
    unable to rollback
    exit status 1

**Comment by methane** [comment]
Can you get packet capture when the error happened?

https://www.wireshark.org/docs/wsug_html_chunked/AppToolstcpdump.html
https://www.wireshark.org/docs/wsug_html_chunked/AppToolsdumpcap.html

For example, `tcpdump -i eth0 -n -s0 port 3306 -w mysql.pcap`

**Comment by woods-chen** [comment]
I ran the script thousands of times on my office computer (Ubuntu 16.04) several months ago, trying to reproduce this error, however got no result. It seems that it only occurred on our production server.  and these days this error seems to have been more frequent, so I will try again to reproduce this error tomorrow (I'm not able to visit the script nor connect to the MySQL server from my PC). Sorry for that I can't test the script nor install tcpdump on the production server, and if it is reproduced on my office computer, I will capture the packages.

**Comment by methane** [comment]
How did you installed the MySQL?  Is it really MySQL?  Or MariaDB?

**Comment by woods-chen** [comment]
It's MySQL 5.6, not MariaDB.
I've been testing the scripts this whole morning to reproduce the error, still not reproduced( now I'm using sqlalchemy, and this afternoon I'll try pymysql).

**Comment by methane** [comment]
What is exact version of MySQL?  5.6.0?
How did you installed it?  `yum install mysql-server`?  Did you add some rpm repository?

**Comment by woods-chen** [comment]
The DBA just told me that he's using Amoeba (version 3.0.5-RC) [https://sourceforge.net/projects/amoeba/](url) as a proxy. So the script on the server is now actually connected to amoeba for querying data. So I'm now testing the script, being connected to the amoeba proxy.
and the MySQL DB version is 5.6.14-log
