### ISSUE TITLE
How to get result from stored procedure?

### ISSUE THREAD

**Issue by svebert** [PyMySQL/PyMySQL#714]
Hi,
I am using Python 3.5 with pymysql 0.9.2 (installed via pip)
I am struggeling to get the result rows from a query:

- I can successfully connect to my database
- I can successfully execute of my stored procedure: GetImageSets()
```*.sql
BEGIN

SELECT name FROM ImageSets;

END
```
Actually this stored procedure called with HeidiSQL returns three rows, which is correct

My problem is to get the rows out of the cursor object. Please see my code:
```*.py
conn = pymysql.connect(sMySqlServer, sUser, sPW, sMySqlDBName, charset='utf8') 
cursor = conn.cursor() 
sQuery = "CALL GetImageSets()"
cursor.execute(sQuery)
res = cursor.fetchall()
```
When I use
```*.py
for row in cursor._rows:
	print(row)
```
it will print my three rows:
> ('General',)
> ('Office',)
> ('Office_Enroll',)

this cannot be the designed way to go. Class members with underscores e.g. "_rows" shouldn't be accessed by users. What is the designed way to go here? I couldn't find anything useful on stackoverflow etc. My problem is, that `res = cursor.fetchall()` unexpectectly returns just "()". res itsself is not empty but empty brackets. Also the cursor object does not have any function besides "_rows" to access the data.

**Comment by methane** [comment]
**[You must not ask a question on issue tracker](https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde#.hdf6lpk11)**

**Comment by svebert** [comment]
... please read the issue. It is at least unexpected behaviour, or even a bug.

**Comment by methane** [comment]
* https://dev.mysql.com/doc/refman/5.7/en/create-procedure.html
* https://www.python.org/dev/peps/pep-0249/#callproc

All misuse caused by lack of knowledge is "unexpected behavior" for someone.
But I'm not free tech support or teacher.

I don't use stored procedure.
I don't use the callproc API.
I don't use feature XXX of MySQL.
I'm very tired to research / learn about feature XXX I don't use only for response on this issue tracker.

Why don't you learn by yourself or use Stackoverflow before use my time without paying?
