### ISSUE TITLE
Sans IO implementation

### ISSUE THREAD

**Issue by mhumpula** [PyMySQL/PyMySQL#912]
_I could not find a better place to discuss this, so sorry for spoiling the issues like this._

Past two years I've been working on projects which were partly written in asyncio and partly in sync python. I was using pymysql for sync part and aiomysql for async part. Though aiomysql is using pymysql as much as possible the large chunks are still copied over to be rewritten in async. Recently I've stumbled upon [sans-io](https://sans-io.readthedocs.io/) concept in python. So the question is: would it make sense for PyMYSQL to split in two parts: one dealing with protocol only and the second with sync interface?

**Comment by methane** [comment]
It is easy to rewrite lowest level protocol in sans-io. But it doesn't solve the problem. aiomysql should still copy and modify the most part, because the lowest level protocol is very simple and it is only a very tiny part of PyMySQL.

Input part:

https://github.com/PyMySQL/PyMySQL/blob/99b703cccb8011692c398caf0c0fbd97b1355e90/pymysql/connections.py#L645-L670

Output part:

https://github.com/PyMySQL/PyMySQL/blob/99b703cccb8011692c398caf0c0fbd97b1355e90/pymysql/connections.py#L626-L635

To reduce copy, we need to rewrite higher level part in sans-io. But it is difficult to me. I have no experience with complex sans-io library.
For example, MySQL starts TLS **during** authentication. We may need to read some files to start TLS. Do you know any nice and clean library handle such protocol?

**Comment by mhumpula** [comment]
So I've dig up to few cases that somehow deal with SSL in the flight. First was [SMTP](https://github.com/agronholm/smtpproto/) and the case with STARTTLS command. As far as I can tell, the user has to react on protocol notification and upgrade its sockets accordingly. The second one was [QUICK](https://github.com/aiortc/aioquic/) which seems to rely on SSL so heavily that it's fully embedded in the protocol implementation and user deals with only passing bytes from and to sockets. The SMTP case seems a little bit like the MySQL protocol.

**Comment by methane** [comment]
Quick looking SMTP:

* STARTTLS is standalone command. So it is much simpler than MySQL protocol.
* Large part is async code. Sans-io part is small. So it is an example that sans-io doesn't reduce duplicated code so much. In case of PyMySQL, the duplicated part (sync and async part) will be bigger than SMTP.

And QUICK:

* It uses OpenSSL in extension. It is not a choice of PyMySQL.

---

I will not try rewriting large part in sans-io manner. My plan in 2021 is just removing Python 2 and Python <3.6 support.

**Comment by mhumpula** [comment]
@methane thanks for the feedback. I was not trying to suggest that you should rewrite the library, just to open up a discussion if it might be a reasonable long term goal for the project. I'm sorry, for not being explicit enough. If you think, from your expertise, that it won't bring any benefits, then it's ok.

**Comment by smurfix** [comment]
> TLS

Trio has a sans-IO TLS implementation. TL-DR: it's somewhat tricky to get that stuff right. It's far easier to just push the TLS module onto the stream and be done with it, but then you no longer have a sans-IO implementation. :-/

Personally I don't see the advantage. It's reasonably easy to convert pymysql to async (I've done it, cf. `trio_mysql`; that package needs conversion to anyio, which is reasonably trivial). That covers most use cases.

While a sans-IO implementation might be helpful if somebody wants to talk to mysql using a different async paradigm, e.g. Twisted or non-monkeypatched Greenlet, I don't think demand is high enough to justify the work.
