### ISSUE TITLE
Updates and deletes are hanging for ~900 seconds

### ISSUE THREAD

**Issue by NadavkOptimalQ** [PyMySQL/PyMySQL#979]
**Describe the bug**
We are running using sqlalchemy 1.3.4 with pymysql 0.10.0 on python 2.7.18. Our code runs with multiprocessing without gevent on AKS.

Along the day some of our updates and deletes take around 900 seconds before finishing. This doesn't happen all the time and we are not able to find the reason this happens

**To Reproduce**
Not really sure how to reproduce this but I can provide logs as requested

**Expected behavior**
All updates and deletes should take the same time without large spikes

**Environment**
- OS: ubuntu 16.04
- Python: 2.7.18
- SQLAlchemy: 1.3.4
- Database: MySQL 5.7
- DBAPI: pymysql 0.10.0

**Additional context**
This has been happening for a few weeks now and is very badly affecting our production
Any help would be much appreciated

**Comment by angusholder** [comment]
That could be a server problem rather than PyMySQL, eg: someone else running a very slow query that locks the tables it's using, causing all other updates/deletes/inserts on those tables to have to wait until it finishes.

Try enabling MySQL's [slow query log](https://dev.mysql.com/doc/refman/5.7/en/slow-query-log.html) and next time you experience the issue check the log using [mysqldumpslow](https://dev.mysql.com/doc/refman/5.7/en/mysqldumpslow.html) to look for a query that takes 900 seconds and held up all the other queries

**Comment by Kremzon** [comment]
We have looked at the slow log and the full process list throughout the day and found nothing that could explain this.
We have our staging with a MySQL deployed on our K8S cluster and we are not seeing these issues. 
We are still investigating with Azure on their side network wise but nothing related has come up so far :(

**Comment by varun-eightfold** [comment]
Seeing the same issue though with AWS RDS. Mysql slow queries does not indicate any problem, is it possible this has to do with TCP connection handling in pymysql?

**Comment by methane** [comment]
* Please use Python 3
* Please provide a minimum steps to reproduce. If you can not provide it, please provide at least pcap file (tcpdump).

**Comment by varun-eightfold** [comment]
It is non-trivial to capture tcp flow given the highly distributed infrastructure and the frequency of occurrence of this issue. Is there anything that can be captured from python itself to help troubleshoot?

**Comment by methane** [comment]
Then I can not help you. You should hire an expert and give an access to your environment/code to them.

**Comment by varun-eightfold** [comment]
I want to thank you for trying to help. For anyone else who comes here in future, I think this issue is the same as described here for redis. Both use python sockets, and both by default do not have a read timeout which results in using the system default timeout of 15m. 
https://github.com/andymccurdy/redis-py/issues/722

**Comment by methane** [comment]
The original issue says just "around 900 seconds before finishing".

So I expect no error after 15m. It is different from andymccurdy/redis-py#722.
