### ISSUE TITLE
Call to non-existent function

### ISSUE THREAD

**Issue by Laranto** [PyMySQL/PyMySQL#981]
In the legacy handshake there is still a call to `_auth.scramble_old_password`
https://github.com/PyMySQL/PyMySQL/blob/master/pymysql/connections.py#L924

This function was deleted in this commit
https://github.com/PyMySQL/PyMySQL/commit/cd61e56190c3ec6ab82934d9475712cd7a170656

**Comment by neye-zhaw** [comment]
this is related to https://github.com/PyMySQL/PyMySQL/pull/922

**Comment by edthedev** [comment]
Since the commit [references a CVE known vulnerability](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2000-0981), I imagine the functionality is not coming back.

Can anyone tell me if I am correct in assuming that the only reason the code would hit this obsolete function call is if newer methods already failed?

Is it safe to assume that this function should be replaced with an exception that asks the user to upgrade the MySQL instance they are connecting to? Or is the situation more nuanced?

**Comment by ddriddle** [comment]
I suggest a better error message be included something similar to what `mysql-connector-python` throws:

```
mysql.connector.errors.NotSupportedError: Authentication with old (insecure) passwords is not supported. For more information, lookup Password Hashing in the latest MySQL manual
```
